<GA> ::= <populationSize> <initialization> <selection> <mating> <replacement> <archive>

##### Population Size #####

<populationSize> ::= "50" | "100" | "150" | "200" | "250" | "300"

##### Initialization #####

<initialization> ::= "Random" | "Parallel Diversified Initialization"

##### Selection #####

<selection> ::= <selectionOperator> <source> <fitnessAssignment>

<selectionOperator> ::= "K Tournament" <tournamentSize>
<tournamentSize> ::= "2"

<source> ::= "Archive and Population"

<fitnessAssignment> ::= <rankingStrategy> <diversityStrategy>
<rankingStrategy> ::= "Raw Fitness"
<diversityStrategy> ::= "K-th Nearest Neighbor"

##### Mating #####

<mating> ::= <matingOperators> <matingStrategy>

<matingOperators> ::= <crossoverOperator> <crossoverProbability> <mutationOperator> <mutationProbability>

<crossoverOperator> ::= "Two Points Crossover" | "Single Point Crossover" | "PMX Crossover" | "Cycle Crossover"
<crossoverProbability> ::= "1.0" | "0.95" | "0.9" | "0.8" | "0.5"

<mutationOperator> ::= "Swap Mutation" | "Insert Mutation" | "Scramble Mutation" | "Inversion Mutation"
<mutationProbability> ::= "0.01" | "0.02" | "0.05" | "0.1" | "0.2" | "0.5" | "0.7" | "0.8" | "0.9" | "1.0"

<matingStrategy> ::= "Generational One Child"

##### Replacement #####

<replacement> ::= "Generational" <elitismSize> <fitnessAssignment>

<elitismSize> ::= "0"

##### Archive #####

<archive> ::= <fitnessAssignment> <archiveSize>
<archiveSize> ::= "0" | "N" | "N * 1.5" | "N * 2"
